language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email:
    recipients:
      - johm@quyo.de
    on_success: always
    on_failure: always
# uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone("https://github.com/Samayel/PrimeSieve.jl.git"); Pkg.build("PrimeSieve");'
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("Brainstorm"); Pkg.test("Brainstorm"; coverage=true)'
after_success:
  - julia -e 'Pkg.add("Coverage")'
  - julia -e 'cd(Pkg.dir("Brainstorm")); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'cd(Pkg.dir("Brainstorm")); using Coverage; Codecov.submit(Codecov.process_folder())'
