language: julia
os:
  - linux
julia:
  - 0.5
# - nightly
env:
  matrix:
    - PRIMESIEVE=true
    - PRIMESIEVE=false
notifications:
  email:
    recipients:
      - johm@quyo.de
    on_success: always
    on_failure: always
before_install:
  - if [ $PRIMESIEVE = "true" ]; then julia -e 'Pkg.clone("https://github.com/Samayel/PrimeSieve.jl.git"); Pkg.build("PrimeSieve")'; fi
# uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Brainstorm")'
  - julia --check-bounds=yes -e 'Pkg.test("Brainstorm"; coverage=true)'
after_success:
  - julia -e '@linux_only Pkg.add("Coverage")'
  - julia -e '@linux_only begin cd(Pkg.dir("Brainstorm")); using Coverage; Coveralls.submit(Coveralls.process_folder()) end'
  - julia -e '@linux_only begin cd(Pkg.dir("Brainstorm")); using Coverage; Codecov.submit(Codecov.process_folder()) end'
