macro lintpragma(s)
end

@lintpragma("Ignore undefined module AutoHashEquals.@auto_hash_equals")
@lintpragma("Ignore undefined module DataStructures.SortedDict")
@lintpragma("Ignore undefined module Iterators.chain")
@lintpragma("Ignore undefined module Iterators.cycle")
@lintpragma("Ignore undefined module Iterators.drop")
@lintpragma("Ignore undefined module Iterators.imap")
@lintpragma("Ignore undefined module Iterators.take")
@lintpragma("Ignore undefined module Lint.lintpkg")
@lintpragma("Ignore undefined module Lists.List")
@lintpragma("Ignore undefined module Lists.ListNode")
@lintpragma("Ignore undefined module Pipe.@pipe")
@lintpragma("Ignore undefined module Reexport.@reexport")
@lintpragma("Ignore undefined module Roots.fzeros")
@lintpragma("Ignore undefined module TaylorSeries.get_coeff")
@lintpragma("Ignore undefined module TaylorSeries.Taylor1")
@lintpragma("Ignore undefined module TaylorSeries.taylor1_variable")

@lintpragma("Ignore undefined module Brainstorm.dropwhile")
@lintpragma("Ignore undefined module Brainstorm.flatten")
@lintpragma("Ignore undefined module Brainstorm.takewhile")
@lintpragma("Ignore undefined module Brainstorm.Math.checked_add")
@lintpragma("Ignore undefined module Brainstorm.Math.checked_sub")
@lintpragma("Ignore undefined module Brainstorm.Math.NumberTheory.coefficient")
@lintpragma("Ignore undefined module Brainstorm.Math.NumberTheory.expand_maclaurin_series")
@lintpragma("Ignore undefined module Brainstorm.@anon")

@lintpragma("Ignore use of undeclared variable _")
