macro lintpragma(s)
end

@lintpragma("Ignore undefined module AutoHashEquals.@auto_hash_equals")
@lintpragma("Ignore undefined module DataStructures.SortedDict")
@lintpragma("Ignore undefined module Lint.lintpkg")
@lintpragma("Ignore undefined module Lists.List")
@lintpragma("Ignore undefined module Lists.ListNode")
@lintpragma("Ignore undefined module Nemo.PowerSeriesRing")
@lintpragma("Ignore undefined module Nemo.QQ")
@lintpragma("Ignore undefined module Nemo.ZZ")
@lintpragma("Ignore undefined module Nemo.coeff")
@lintpragma("Ignore undefined module Nemo.divexact")
@lintpragma("Ignore undefined module Nemo.fac")
@lintpragma("Ignore undefined module Pipe.@pipe")
@lintpragma("Ignore undefined module Reexport.@reexport")
@lintpragma("Ignore undefined module Roots.fzeros")

@lintpragma("Ignore undefined module Brainstorm.dropwhile")
@lintpragma("Ignore undefined module Brainstorm.flatten")
@lintpragma("Ignore undefined module Brainstorm.takewhile")
@lintpragma("Ignore undefined module Brainstorm.Math.checked_add")
@lintpragma("Ignore undefined module Brainstorm.Math.checked_sub")

@lintpragma("Ignore use of undeclared variable _")
